=begin
#PDFGen API

#The PDFGen API for HTML to PDF generation.

The version of the OpenAPI document: 1.0
Contact: support@pdfgen.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ListJobsResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ListJobsResponse do
  let(:instance) { OpenapiClient::ListJobsResponse.new }

  describe 'test an instance of ListJobsResponse' do
    it 'should create an instance of ListJobsResponse' do
      expect(instance).to be_instance_of(OpenapiClient::ListJobsResponse)
    end
  end
  describe 'test attribute "jobs"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
