=begin
#PDFGen API

#The PDFGen API for HTML to PDF generation.

The version of the OpenAPI document: 1.0
Contact: support@pdfgen.dev
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

# Common files
require 'pdfgenClient/api_client'
require 'pdfgenClient/api_error'
require 'pdfgenClient/version'
require 'pdfgenClient/configuration'

# Models
require 'pdfgenClient/models/create_template_request'
require 'pdfgenClient/models/error_response'
require 'pdfgenClient/models/generate_pdf_request'
require 'pdfgenClient/models/job_response'
require 'pdfgenClient/models/list_jobs_response'
require 'pdfgenClient/models/list_templates_response'
require 'pdfgenClient/models/template_response'
require 'pdfgenClient/models/update_template_request'

# APIs
require 'pdfgenClient/api/jobs_api'
require 'pdfgenClient/api/pdf_api'
require 'pdfgenClient/api/templates_api'

module PdfgenClient
  class << self
    # Customize default settings for the SDK using block.
    #   PdfgenClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
